import {PrismaClient,Role} from "@prisma/client";
import bcrypt from "bcryptjs";

const db=new PrismaClient();

async function main(){
  const pw=process.env.ADMIN_PASSWORD;
  if(!pw)throw new Error("ADMIN_PASSWORD required");
  const email=(process.env.ADMIN_EMAIL||"uchennaokoro51@gmail.com").trim().toLowerCase();
  const previousAdminEmail="uchennaokoro697@gmail.com";
  if(email!==previousAdminEmail){
    const previous=await db.user.findUnique({where:{email:previousAdminEmail}});
    const target=await db.user.findUnique({where:{email}});
    if(previous && !target) await db.user.update({where:{email:previousAdminEmail},data:{email}});
  }
  const hash=await bcrypt.hash(pw,12);

  const resetAdmin2FA=process.env.RESET_ADMIN_2FA==="true";
  await db.user.updateMany({where:{role:Role.READ_ONLY_ADMIN},data:{role:Role.READ_WRITE_ADMIN}});
  await db.user.upsert({
    where:{email},
    update:{passwordHash:hash,role:Role.ADMIN,...(resetAdmin2FA?{totpSecret:null,totpEnabled:false}:{})},
    create:{email,fullName:"Platform Administrator",passwordHash:hash,role:Role.ADMIN,wallet:{create:{}}}
  });

  const rows=[
    ["AAPL","Apple",333.69,1.02],["META","Meta Platforms",728.08,.30],["TSLA","Tesla",370.59,4.65],
    ["GOOGL","Alphabet",343.50,1.56],["NVDA","NVIDIA",233.95,1.34],["JPM","JPMorgan Chase",332.38,-.24],
    ["JNJ","Johnson & Johnson",256.03,-1.02],["MSFT","Microsoft",517.53,.92],["AMZN","Amazon",251.52,1.33],
    ["NFLX","Netflix",67.06,-1.16]
  ];
  const sectors:Record<string,string>={AAPL:"Technology",META:"Communication Services",TSLA:"Consumer Cyclical",GOOGL:"Communication Services",NVDA:"Technology",JPM:"Financial Services",JNJ:"Healthcare",MSFT:"Technology",AMZN:"Consumer Cyclical",NFLX:"Communication Services"};
  for(const x of rows){
    await db.stock.upsert({
      where:{symbol:x[0] as string},
      update:{name:x[1] as string,price:Number(x[2]),changePercent:Number(x[3]),sector:sectors[x[0] as string]},
      create:{symbol:x[0] as string,name:x[1] as string,price:Number(x[2]),changePercent:Number(x[3]),sector:sectors[x[0] as string]}
    });
  }

  const products=[
    {name:"Tesla Model 3 — Stealth Grey",slug:"tesla-model-3-stealth-grey",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 catalog variant in Stealth Grey. Price is a catalog/reference value for this inventory listing.",price:38630,currency:"USD",downPayment:Math.round(38630*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$38,630",featured:true},
    {name:"Tesla Model 3 — Pearl White",slug:"tesla-model-3-pearl-white",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 catalog variant in Pearl White. Price is a catalog/reference value for this inventory listing.",price:40130,currency:"USD",downPayment:Math.round(40130*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$40,130",featured:false},
    {name:"Tesla Model 3 — Diamond Black",slug:"tesla-model-3-diamond-black",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 catalog variant in Diamond Black. Price is a catalog/reference value for this inventory listing.",price:40630,currency:"USD",downPayment:Math.round(40630*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$40,630",featured:false},
    {name:"Tesla Model 3 — Ultra Red",slug:"tesla-model-3-ultra-red",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 catalog variant in Ultra Red. Price is a catalog/reference value for this inventory listing.",price:42130,currency:"USD",downPayment:Math.round(42130*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$42,130",featured:false},
    {name:"Tesla Model Y — Stealth Grey",slug:"tesla-model-y-stealth-grey",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y catalog variant in Stealth Grey. Price is a catalog/reference value for this inventory listing.",price:39990,currency:"USD",downPayment:Math.round(39990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$39,990",featured:true},
    {name:"Tesla Model Y — Pearl White",slug:"tesla-model-y-pearl-white",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y catalog variant in Pearl White. Price is a catalog/reference value for this inventory listing.",price:41490,currency:"USD",downPayment:Math.round(41490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$41,490",featured:false},
    {name:"Tesla Model Y — Diamond Black",slug:"tesla-model-y-diamond-black",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y catalog variant in Diamond Black. Price is a catalog/reference value for this inventory listing.",price:41990,currency:"USD",downPayment:Math.round(41990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$41,990",featured:false},
    {name:"Tesla Model Y — Ultra Red",slug:"tesla-model-y-ultra-red",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y catalog variant in Ultra Red. Price is a catalog/reference value for this inventory listing.",price:43490,currency:"USD",downPayment:Math.round(43490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$43,490",featured:false},
    {name:"Tesla Model S — Stealth Grey",slug:"tesla-model-s-stealth-grey",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model S catalog variant in Stealth Grey. Price is a catalog/reference value for this inventory listing.",price:84990,currency:"USD",downPayment:Math.round(84990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20S.jpg",sourceUrl:"https://www.tesla.com/models",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$84,990",featured:true},
    {name:"Tesla Model S — Pearl White",slug:"tesla-model-s-pearl-white",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model S catalog variant in Pearl White. Price is a catalog/reference value for this inventory listing.",price:86490,currency:"USD",downPayment:Math.round(86490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20S.jpg",sourceUrl:"https://www.tesla.com/models",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$86,490",featured:false},
    {name:"Tesla Model S — Diamond Black",slug:"tesla-model-s-diamond-black",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model S catalog variant in Diamond Black. Price is a catalog/reference value for this inventory listing.",price:86990,currency:"USD",downPayment:Math.round(86990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20S.jpg",sourceUrl:"https://www.tesla.com/models",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$86,990",featured:false},
    {name:"Tesla Model S — Ultra Red",slug:"tesla-model-s-ultra-red",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model S catalog variant in Ultra Red. Price is a catalog/reference value for this inventory listing.",price:88490,currency:"USD",downPayment:Math.round(88490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20S.jpg",sourceUrl:"https://www.tesla.com/models",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$88,490",featured:false},
    {name:"Tesla Model X — Stealth Grey",slug:"tesla-model-x-stealth-grey",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model X catalog variant in Stealth Grey. Price is a catalog/reference value for this inventory listing.",price:89990,currency:"USD",downPayment:Math.round(89990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20X.jpg",sourceUrl:"https://www.tesla.com/modelx",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$89,990",featured:true},
    {name:"Tesla Model X — Pearl White",slug:"tesla-model-x-pearl-white",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model X catalog variant in Pearl White. Price is a catalog/reference value for this inventory listing.",price:91490,currency:"USD",downPayment:Math.round(91490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20X.jpg",sourceUrl:"https://www.tesla.com/modelx",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$91,490",featured:false},
    {name:"Tesla Model X — Diamond Black",slug:"tesla-model-x-diamond-black",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model X catalog variant in Diamond Black. Price is a catalog/reference value for this inventory listing.",price:91990,currency:"USD",downPayment:Math.round(91990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20X.jpg",sourceUrl:"https://www.tesla.com/modelx",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$91,990",featured:false},
    {name:"Tesla Model X — Ultra Red",slug:"tesla-model-x-ultra-red",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model X catalog variant in Ultra Red. Price is a catalog/reference value for this inventory listing.",price:93490,currency:"USD",downPayment:Math.round(93490*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20X.jpg",sourceUrl:"https://www.tesla.com/modelx",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$93,490",featured:false},
    {name:"Tesla Cybertruck — Stainless Steel",slug:"tesla-cybertruck-stainless-steel",brand:"Tesla",category:"Electric Trucks",description:"Tesla Cybertruck catalog variant in Stainless Steel. Price is a catalog/reference value for this inventory listing.",price:74990,currency:"USD",downPayment:Math.round(74990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20cybertruck.jpg",sourceUrl:"https://www.tesla.com/cybertruck",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$74,990",featured:true},
    {name:"Tesla Cybertruck — Black",slug:"tesla-cybertruck-black",brand:"Tesla",category:"Electric Trucks",description:"Tesla Cybertruck catalog variant in Black. Price is a catalog/reference value for this inventory listing.",price:79990,currency:"USD",downPayment:Math.round(79990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20cybertruck.jpg",sourceUrl:"https://www.tesla.com/cybertruck",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$79,990",featured:false},
    {name:"Tesla Cybertruck — White",slug:"tesla-cybertruck-white",brand:"Tesla",category:"Electric Trucks",description:"Tesla Cybertruck catalog variant in White. Price is a catalog/reference value for this inventory listing.",price:84990,currency:"USD",downPayment:Math.round(84990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20cybertruck.jpg",sourceUrl:"https://www.tesla.com/cybertruck",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$84,990",featured:false},
    {name:"Tesla Cybertruck — Red",slug:"tesla-cybertruck-red",brand:"Tesla",category:"Electric Trucks",description:"Tesla Cybertruck catalog variant in Red. Price is a catalog/reference value for this inventory listing.",price:99990,currency:"USD",downPayment:Math.round(99990*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20cybertruck.jpg",sourceUrl:"https://www.tesla.com/cybertruck",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$99,990",featured:false},
    {name:"Tesla Semi — White",slug:"tesla-semi-white",brand:"Tesla",category:"Electric Trucks",description:"Tesla Semi catalog variant in White. Price is a catalog/reference value for this inventory listing.",price:250000,currency:"USD",downPayment:Math.round(250000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Semi%201.jpg",sourceUrl:"https://www.tesla.com/semi",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$250,000",featured:false},
    {name:"Tesla Semi — Black",slug:"tesla-semi-black",brand:"Tesla",category:"Electric Trucks",description:"Tesla Semi catalog variant in Black. Price is a catalog/reference value for this inventory listing.",price:255000,currency:"USD",downPayment:Math.round(255000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Semi%201.jpg",sourceUrl:"https://www.tesla.com/semi",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$255,000",featured:false},
    {name:"Tesla Semi — Silver",slug:"tesla-semi-silver",brand:"Tesla",category:"Electric Trucks",description:"Tesla Semi catalog variant in Silver. Price is a catalog/reference value for this inventory listing.",price:260000,currency:"USD",downPayment:Math.round(260000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Semi%201.jpg",sourceUrl:"https://www.tesla.com/semi",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$260,000",featured:false},
    {name:"Tesla Semi — Red",slug:"tesla-semi-red",brand:"Tesla",category:"Electric Trucks",description:"Tesla Semi catalog variant in Red. Price is a catalog/reference value for this inventory listing.",price:265000,currency:"USD",downPayment:Math.round(265000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Semi%201.jpg",sourceUrl:"https://www.tesla.com/semi",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$265,000",featured:false},
    {name:"Tesla Roadster — White",slug:"tesla-roadster-white",brand:"Tesla",category:"Electric Sports Cars",description:"Tesla Roadster catalog variant in White. Price is a catalog/reference value for this inventory listing.",price:200000,currency:"USD",downPayment:Math.round(200000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Roadster.JPG",sourceUrl:"https://www.tesla.com/roadster",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$200,000",featured:false},
    {name:"Tesla Roadster — Black",slug:"tesla-roadster-black",brand:"Tesla",category:"Electric Sports Cars",description:"Tesla Roadster catalog variant in Black. Price is a catalog/reference value for this inventory listing.",price:205000,currency:"USD",downPayment:Math.round(205000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Roadster.JPG",sourceUrl:"https://www.tesla.com/roadster",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$205,000",featured:false},
    {name:"Tesla Roadster — Silver",slug:"tesla-roadster-silver",brand:"Tesla",category:"Electric Sports Cars",description:"Tesla Roadster catalog variant in Silver. Price is a catalog/reference value for this inventory listing.",price:210000,currency:"USD",downPayment:Math.round(210000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Roadster.JPG",sourceUrl:"https://www.tesla.com/roadster",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$210,000",featured:false},
    {name:"Tesla Roadster — Red",slug:"tesla-roadster-red",brand:"Tesla",category:"Electric Sports Cars",description:"Tesla Roadster catalog variant in Red. Price is a catalog/reference value for this inventory listing.",price:215000,currency:"USD",downPayment:Math.round(215000*0.20),imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Roadster.JPG",sourceUrl:"https://www.tesla.com/roadster",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$215,000",featured:false}
  ];
  const extraColorProducts=[
    {name:"Tesla Model 3 — Frost Blue Metallic",slug:"tesla-model-3-frost-blue-metallic",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 rear-wheel-drive catalog variant in Frost Blue Metallic.",price:36990,currency:"USD",downPayment:7398,imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$36,990",featured:false},
    {name:"Tesla Model 3 — Quicksilver",slug:"tesla-model-3-quicksilver",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model 3 rear-wheel-drive catalog variant in Quicksilver.",price:36990,currency:"USD",downPayment:7398,imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$36,990",featured:false},
    {name:"Tesla Model Y — Glacier Blue",slug:"tesla-model-y-glacier-blue",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y rear-wheel-drive catalog variant in Glacier Blue.",price:39990,currency:"USD",downPayment:7998,imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$39,990",featured:false},
    {name:"Tesla Model Y — Quicksilver",slug:"tesla-model-y-quicksilver",brand:"Tesla",category:"Electric Vehicles",description:"Tesla Model Y rear-wheel-drive catalog variant in Quicksilver.",price:39990,currency:"USD",downPayment:7998,imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"$39,990",featured:false}
  ];

  // Keep the customer inventory focused on Tesla vehicles only. Existing Starlink, energy and other non-vehicle records are retained but hidden/deactivated.
  await db.product.updateMany({where:{brand:{not:"Tesla"}},data:{active:false,stockQuantity:0,availability:"OUT_OF_STOCK"}});
  await db.product.updateMany({where:{brand:"Tesla"},data:{active:false,stockQuantity:0,availability:"OUT_OF_STOCK"}});
  const currentVehicleProducts=[...products,...extraColorProducts].filter(p=>p.slug.startsWith("tesla-model-3-")||p.slug.startsWith("tesla-model-y-")||p.slug.startsWith("tesla-cybertruck-"));
  for(const p of currentVehicleProducts){
    await db.product.upsert({where:{slug:p.slug},update:{...p,active:true,stockQuantity:5,availability:"AVAILABLE"},create:{...p,active:true,stockQuantity:5,availability:"AVAILABLE"}});
  }
}

main().catch(e=>{console.error("Seed failed",e);process.exitCode=1}).finally(()=>db.$disconnect());