import {PrismaClient,Role} from "@prisma/client";
import bcrypt from "bcryptjs";

const db=new PrismaClient();

async function main(){
  const pw=process.env.ADMIN_PASSWORD;
  if(!pw)throw new Error("ADMIN_PASSWORD required");
  const email=(process.env.ADMIN_EMAIL||"admin@example.com").trim().toLowerCase();
  const hash=await bcrypt.hash(pw,12);

  const resetAdmin2FA=process.env.RESET_ADMIN_2FA==="true";
  await db.user.upsert({
    where:{email},
    update:{passwordHash:hash,role:Role.ADMIN,...(resetAdmin2FA?{totpSecret:null,totpEnabled:false}:{})},
    create:{email,fullName:"Platform Administrator",passwordHash:hash,role:Role.ADMIN,wallet:{create:{}}}
  });

  const rows=[
    ["AAPL","Apple",226.96,.84],["META","Meta Platforms",746.98,1.21],["TSLA","Tesla",442.79,-.42],
    ["GOOGL","Alphabet",256.09,.64],["NVDA","NVIDIA",185.48,1.34],["JPM","JPMorgan Chase",310.45,.37],
    ["JNJ","Johnson & Johnson",175.12,-.18],["MSFT","Microsoft",510.78,.92],["AMZN","Amazon",231.45,.58],
    ["NFLX","Netflix",1194.3,.73]
  ];
  for(const x of rows){
    await db.stock.upsert({
      where:{symbol:x[0] as string},
      update:{name:x[1] as string,price:Number(x[2]),changePercent:Number(x[3])},
      create:{symbol:x[0] as string,name:x[1] as string,price:Number(x[2]),changePercent:Number(x[3])}
    });
  }

  const products=[
    {name:"Tesla Model 3",slug:"tesla-model-3",brand:"Tesla",category:"Electric Vehicles",description:"Tesla compact electric sedan.",price:38630,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%203%20Highland%20RWD%20Pearl%20White%20Multi-Coat%2001.jpg",sourceUrl:"https://www.tesla.com/model3",imageCredit:"Wikimedia Commons",imageLicense:"CC BY-SA",priceLabel:"Starting at $38,630",featured:true},
    {name:"Tesla Model Y",slug:"tesla-model-y",brand:"Tesla",category:"Electric Vehicles",description:"Tesla electric midsize SUV/crossover.",price:39990,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20Y%20%28Facelift%29%20%E2%80%93%20f%2005052026.jpg",sourceUrl:"https://www.tesla.com/modely",imageCredit:"Wikimedia Commons",imageLicense:"CC BY-SA",priceLabel:"From $39,990",featured:true},
    {name:"Tesla Model S",slug:"tesla-model-s",brand:"Tesla",category:"Electric Vehicles",description:"Tesla premium electric sedan. Pricing varies by configuration and market.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20S.jpg",sourceUrl:"https://www.tesla.com/models",imageCredit:"Wikimedia Commons",imageLicense:"CC BY-SA",priceLabel:"Check current Tesla pricing",featured:true},
    {name:"Tesla Model X",slug:"tesla-model-x",brand:"Tesla",category:"Electric Vehicles",description:"Tesla electric SUV with falcon-wing doors. Pricing varies by configuration and market.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Model%20X.jpg",sourceUrl:"https://www.tesla.com/modelx",imageCredit:"Wikimedia Commons",imageLicense:"CC BY-SA",priceLabel:"Check current Tesla pricing"},
    {name:"Tesla Cybertruck",slug:"tesla-cybertruck",brand:"Tesla",category:"Electric Trucks",description:"Tesla stainless-steel electric pickup truck.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20cybertruck.jpg",sourceUrl:"https://www.tesla.com/cybertruck",imageCredit:"X120412 / Wikimedia Commons",imageLicense:"CC0",priceLabel:"Check current Tesla pricing",featured:true},
    {name:"Tesla Semi",slug:"tesla-semi",brand:"Tesla",category:"Electric Trucks",description:"Tesla all-electric Class 8 semi-trailer truck.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Semi%201.jpg",sourceUrl:"https://www.tesla.com/semi",imageCredit:"Wikimedia Commons",imageLicense:"CC BY-SA",priceLabel:"Commercial pricing / availability"},
    {name:"Tesla Roadster",slug:"tesla-roadster",brand:"Tesla",category:"Electric Sports Cars",description:"Tesla all-electric sports car; availability and pricing are subject to Tesla updates.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Roadster.JPG",sourceUrl:"https://www.tesla.com/roadster",imageCredit:"Thomas doerfer / Wikimedia Commons",imageLicense:"CC BY 3.0",priceLabel:"Reserve / check current pricing"},
    {name:"Starlink Standard V5",slug:"starlink-standard-v5",brand:"Starlink",category:"Satellite Internet",description:"Starlink Standard hardware for home and fixed-location connectivity.",price:null,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Check current Nigerian price",featured:true},
    {name:"Starlink Mini",slug:"starlink-mini",brand:"Starlink",category:"Satellite Internet",description:"Compact portable Starlink kit for internet on the go.",price:140860,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"NGN 140,860",featured:true},
    {name:"Starlink Standard 4",slug:"starlink-standard-4",brand:"Starlink",category:"Satellite Internet",description:"Standard Starlink hardware for residential connectivity.",price:null,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Check current Nigerian price"},
    {name:"Starlink Standard 4 X",slug:"starlink-standard-4-x",brand:"Starlink",category:"Satellite Internet",description:"Starlink Standard 4 X hardware option.",price:null,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Check current Nigerian price"},
    {name:"Starlink Performance Gen 3",slug:"starlink-performance-gen-3",brand:"Starlink",category:"Business Connectivity",description:"Starlink Performance hardware for higher-demand business connectivity.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Check current pricing"},
    {name:"Starlink Enterprise",slug:"starlink-enterprise",brand:"Starlink",category:"Business Connectivity",description:"Enterprise-grade Starlink connectivity hardware and service reference listing.",price:null,currency:"USD",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Contact Starlink for pricing"},
    {name:"Starlink Router 3",slug:"starlink-router-3",brand:"Starlink",category:"Networking Accessories",description:"Starlink Router 3 accessory for compatible Starlink hardware.",price:212000,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"NGN 212,000"},
    {name:"Starlink Router Mini",slug:"starlink-router-mini",brand:"Starlink",category:"Networking Accessories",description:"Compact Wi-Fi 6 mesh router accessory for compatible Starlink kits.",price:140860,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"Check current Nigerian price"},
    {name:"Starlink Cable 45m",slug:"starlink-cable-45m",brand:"Starlink",category:"Networking Accessories",description:"45-meter Starlink cable accessory.",price:250300,currency:"NGN",imageUrl:"https://commons.wikimedia.org/wiki/Special:FilePath/Starlink%20dish%2001.webp",sourceUrl:"https://starlink.com/ng/public/shop",imageCredit:"Wikimedia Commons",imageLicense:"See source",priceLabel:"NGN 250,300"},
    {name:"Ford Mustang Mach-E",slug:"ford-mustang-mach-e",brand:"Ford",category:"Electric Vehicles",description:"Electric crossover reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.ford.com/mustang/mach-e/"},
    {name:"Ford F-150 Lightning",slug:"ford-f150-lightning",brand:"Ford",category:"Electric Trucks",description:"Electric pickup truck reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.ford.com/trucks/f150/f150-lightning/"},
    {name:"Rivian R1T",slug:"rivian-r1t",brand:"Rivian",category:"Electric Trucks",description:"Electric adventure pickup truck reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://rivian.com/r1t"},
    {name:"Rivian R1S",slug:"rivian-r1s",brand:"Rivian",category:"Electric SUVs",description:"Electric adventure SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://rivian.com/r1s"},
    {name:"Lucid Air",slug:"lucid-air",brand:"Lucid",category:"Electric Vehicles",description:"Premium electric sedan reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://lucidmotors.com/air"},
    {name:"Mercedes-Benz EQS",slug:"mercedes-eqs",brand:"Mercedes-Benz",category:"Electric Vehicles",description:"Luxury electric sedan reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.mbusa.com/en/vehicles/class/eqs/sedan/type-amg-eqs"},
    {name:"BMW iX",slug:"bmw-ix",brand:"BMW",category:"Electric SUVs",description:"Premium electric SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.bmwusa.com/vehicles/all-electric/ix/sports-activity-vehicle/overview.html"},
    {name:"Toyota Land Cruiser",slug:"toyota-land-cruiser",brand:"Toyota",category:"SUVs",description:"Full-size SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.toyota.com/landcruiser/"},
    {name:"Toyota RAV4",slug:"toyota-rav4",brand:"Toyota",category:"SUVs",description:"Compact SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.toyota.com/rav4/"},
    {name:"Porsche Taycan",slug:"porsche-taycan",brand:"Porsche",category:"Electric Sports Cars",description:"High-performance electric sports sedan reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1614200179396-2bdb77ebf0f4?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.porsche.com/usa/models/taycan/"},
    {name:"Porsche 911",slug:"porsche-911",brand:"Porsche",category:"Sports Cars",description:"Porsche 911 sports car reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.porsche.com/usa/models/911/"},
    {name:"Range Rover",slug:"range-rover",brand:"Land Rover",category:"Luxury SUVs",description:"Luxury SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.landroverusa.com/range-rover/index.html"},
    {name:"Mercedes-Benz G-Class",slug:"mercedes-g-class",brand:"Mercedes-Benz",category:"Luxury SUVs",description:"Luxury off-road SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.mbusa.com/en/vehicles/class/g-class/suv/type-amg-g63"},
    {name:"Chevrolet Silverado EV",slug:"chevrolet-silverado-ev",brand:"Chevrolet",category:"Electric Trucks",description:"Full-size electric pickup reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.chevrolet.com/electric/silverado-ev"},
    {name:"GMC Hummer EV",slug:"gmc-hummer-ev",brand:"GMC",category:"Electric Trucks",description:"Electric pickup and SUV family reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.gmc.com/electric/hummer-ev"},
    {name:"Jeep Wrangler 4xe",slug:"jeep-wrangler-4xe",brand:"Jeep",category:"Plug-in Hybrid SUVs",description:"Plug-in hybrid off-road SUV reference listing.",price:null,currency:"USD",imageUrl:"https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",sourceUrl:"https://www.jeep.com/wrangler/4xe.html"}
  ];
  for(const p of products)await db.product.upsert({where:{slug:p.slug},update:p,create:p});
}

main().catch(e=>{console.error("Seed failed",e);process.exitCode=1}).finally(()=>db.$disconnect());