"use client";
import {useMemo,useState} from "react";
type Product={id:string;name:string;brand:string;category:string;description:string;price:number|null;currency:string;imageUrl:string;sourceUrl:string;imageCredit:string|null;imageLicense:string|null;priceLabel:string|null;downPayment:number|null};
export default function ProductsBrowser({products,title="Products",subtitle="Browse reference products with matched images and sourced pricing. These listings are not purchase orders or investment products."}:{products:Product[];title?:string;subtitle?:string}){
 const [q,setQ]=useState(""); const [category,setCategory]=useState("All");
 const categories=["All",...Array.from(new Set(products.map(p=>p.category)))];
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&[p.name,p.brand,p.category,p.description].join(" ").toLowerCase().includes(q.toLowerCase())),[products,q,category]);
 return <><div className="topbar"><div><p className="eyebrow">Elite Auto inventory</p><h1>{title}</h1><p className="muted">{subtitle}</p></div><span className="badge">Reference catalog</span></div>
 <div className="inventory-count"><strong>Available Vehicles</strong><span>Showing {filtered.length} of {products.length} vehicles</span></div><div className="card product-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Tesla, Model Y, electric vehicle..." aria-label="Search products"/><div className="filter-row">{categories.map(c=><button key={c} className={category===c?"btn":"btn secondary"} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
 <div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={p.imageUrl} alt={p.name}/></div><div className="product-body"><div className="product-meta"><span>{p.brand}</span><span>{p.category}</span></div><h2>{p.name}</h2><p className="muted">{p.description}</p><div className="product-price">{p.price!==null?new Intl.NumberFormat("en-US",{style:"currency",currency:p.currency,maximumFractionDigits:0}).format(p.price):"Price varies"}</div>{p.downPayment!==null&&<div className="muted" style={{marginTop:6}}>Down payment (20%): {new Intl.NumberFormat("en-US",{style:"currency",currency:p.currency,maximumFractionDigits:0}).format(p.downPayment)}</div>}<div className="product-actions"><a className="btn" href={"/inventory/"+p.id}>View details</a></div><small className="muted">{p.priceLabel||"Price subject to change"}{p.imageCredit?<> · Image: {p.imageCredit}</>:null}{p.imageLicense?<> · {p.imageLicense}</>:null}</small></div></article>)}</div>{!filtered.length&&<div className="card empty">No matching products found.</div>}<p className="muted product-note">Product prices are reference values captured from source pages and can change by country, configuration, taxes, fees and date. Images are sourced from Wikimedia Commons under their stated licenses.</p></>;
}