"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
type Product={id:string;name:string;brand:string;category:string;description:string;price:number|null;currency:string;imageUrl:string;priceLabel:string|null;downPayment:number|null;modelYear:number|null;trim:string|null;exteriorColor:string|null;drivetrain:string|null;rangeMiles:number|null;availableColors:string[];stockQuantity:number};
const money=(n:number,c:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(n);
export default function ProductsBrowser({products,title="Inventory",subtitle="Browse available Tesla and Starlink products and request a purchase."}:{products:Product[];title?:string;subtitle?:string}){
 const[q,setQ]=useState("");const[category,setCategory]=useState("All");const categories=["All",...Array.from(new Set(products.map(p=>p.category)))];
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&[p.name,p.brand,p.category,p.description].join(" ").toLowerCase().includes(q.toLowerCase())),[products,q,category]);
 return <><div className="topbar"><div><p className="eyebrow">Tesla inventory</p><h1>{title}</h1><p className="muted">{subtitle}</p></div><Link className="btn secondary" href="/purchases">My purchases</Link></div>
 <div className="inventory-count"><strong>Available vehicles</strong><span>{filtered.length} of {products.length}</span></div>
 <div className="card product-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Model 3, Model Y, Cybertruck..." aria-label="Search inventory"/><div className="filter-row">{categories.map(c=><button key={c} className={category===c?"btn":"btn secondary"} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
 <div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={p.imageUrl} alt={p.name}/><span className="badge" style={{position:"absolute",top:10,left:10}}>Available</span></div><div className="product-body"><div className="product-meta"><span>{p.brand}</span><span>{p.category}</span></div><h2>{p.name}</h2><p className="muted">{p.description}</p><div className="product-price">{p.price!==null?money(p.price,p.currency):"Price on request"}</div>{(p.modelYear||p.trim||p.exteriorColor||p.drivetrain||p.rangeMiles)&&<div className="muted" style={{marginTop:8}}>{[p.modelYear,p.trim,p.exteriorColor,p.drivetrain,p.rangeMiles?p.rangeMiles+" mi":null].filter(Boolean).join(" · ")}</div>}{p.availableColors?.length>1&&<div className="color-options"><span className="muted">Available colors:</span> {p.availableColors.join(" · ")}</div>}{p.downPayment!==null&&<div className="muted" style={{marginTop:6}}>Down payment: {money(p.downPayment,p.currency)}</div>}<div className="product-actions"><Link className="btn" href={"/inventory/"+p.id}>View & purchase</Link></div>{p.priceLabel&&<small className="muted">{p.priceLabel}</small>}</div></article>)}</div>{!filtered.length&&<div className="card empty">No matching vehicles found.</div>}</>;
}