export const TESLA_MODEL_COLORS=["Stealth Grey","Pearl White Multi-Coat","Diamond Black","Frost Blue Metallic","Ultra Red","Quicksilver"] as const;
export const VERIFIED_TESLA:Record<string,any>={
"tesla-model-3-stealth-grey":{name:"Tesla Model 3 — Rear-Wheel Drive · Stealth Grey",price:36990,downPayment:7398,modelYear:2026,trim:"Rear-Wheel Drive",exteriorColor:"Stealth Grey",interiorColor:"All Black Partial Premium",drivetrain:"Rear-Wheel Drive",rangeMiles:321,availableColors:TESLA_MODEL_COLORS},
"tesla-model-3-pearl-white":{name:"Tesla Model 3 — Premium Rear-Wheel Drive · Pearl White",price:42490,downPayment:8498,modelYear:2026,trim:"Premium Rear-Wheel Drive",exteriorColor:"Pearl White Multi-Coat",interiorColor:"Black Premium",drivetrain:"Rear-Wheel Drive",rangeMiles:343,availableColors:TESLA_MODEL_COLORS},
"tesla-model-3-diamond-black":{name:"Tesla Model 3 — Premium All-Wheel Drive · Diamond Black",price:47490,downPayment:9498,modelYear:2026,trim:"Premium All-Wheel Drive",exteriorColor:"Diamond Black",interiorColor:"Black and White Premium",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:346,availableColors:TESLA_MODEL_COLORS},
"tesla-model-3-ultra-red":{name:"Tesla Model 3 — Performance All-Wheel Drive · Ultra Red",price:54990,downPayment:10998,modelYear:2026,trim:"Performance All-Wheel Drive",exteriorColor:"Ultra Red",interiorColor:"Black Premium",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:309,availableColors:TESLA_MODEL_COLORS},
"tesla-model-y-stealth-grey":{name:"Tesla Model Y — Rear-Wheel Drive · Stealth Grey",price:39990,downPayment:7998,modelYear:2026,trim:"Rear-Wheel Drive",exteriorColor:"Stealth Grey",interiorColor:"All Black",drivetrain:"Rear-Wheel Drive",rangeMiles:321,availableColors:TESLA_MODEL_COLORS},
"tesla-model-y-pearl-white":{name:"Tesla Model Y — All-Wheel Drive · Pearl White",price:41990,downPayment:8398,modelYear:2026,trim:"All-Wheel Drive",exteriorColor:"Pearl White Multi-Coat",interiorColor:"All Black",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:294,availableColors:TESLA_MODEL_COLORS},
"tesla-model-y-diamond-black":{name:"Tesla Model Y — Premium All-Wheel Drive · Diamond Black",price:49990,downPayment:9998,modelYear:2026,trim:"Premium All-Wheel Drive",exteriorColor:"Diamond Black",interiorColor:"Black and White Premium",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:327,availableColors:TESLA_MODEL_COLORS},
"tesla-model-y-ultra-red":{name:"Tesla Model Y — Performance All-Wheel Drive · Ultra Red",price:57990,downPayment:11598,modelYear:2026,trim:"Performance All-Wheel Drive",exteriorColor:"Ultra Red",interiorColor:"Premium Performance Interior",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:306,availableColors:TESLA_MODEL_COLORS},
"tesla-cybertruck-stainless-steel":{name:"Tesla Cybertruck — Dual Motor All-Wheel Drive",price:74990,downPayment:14998,modelYear:2026,trim:"Dual Motor All-Wheel Drive",exteriorColor:"Stainless Steel",interiorColor:"Tactical Grey",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:325,availableColors:["Stainless Steel"]},
"tesla-cybertruck-black":{name:"Tesla Cybertruck — Premium All-Wheel Drive",price:84990,downPayment:16998,modelYear:2026,trim:"Premium All-Wheel Drive",exteriorColor:"Stainless Steel",interiorColor:"Tactical Grey",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:325,availableColors:["Stainless Steel"]},
"tesla-cybertruck-white":{name:"Tesla Cybertruck — Cyberbeast",price:99990,downPayment:19998,modelYear:2026,trim:"Cyberbeast",exteriorColor:"Stainless Steel",interiorColor:"Tactical Grey",drivetrain:"Tri-Motor All-Wheel Drive",rangeMiles:320,availableColors:["Stainless Steel"]},
"tesla-cybertruck-red":{name:"Tesla Cybertruck — Premium All-Wheel Drive · Reference",price:84990,downPayment:16998,modelYear:2026,trim:"Premium All-Wheel Drive",exteriorColor:"Stainless Steel",interiorColor:"Tactical Grey",drivetrain:"Dual Motor All-Wheel Drive",rangeMiles:325,availableColors:["Stainless Steel"]}
};