import {redirect} from "next/navigation";
import {getUser} from "../../lib/auth";
import {db} from "../../lib/prisma";
import Link from "next/link";
const money=(n:number,c="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(n);

export default async function Purchases({searchParams}:{searchParams?:Promise<{status?:string}>}){
 const u=await getUser(); if(!u)redirect("/login");
 const params=searchParams?await searchParams:{};
 const purchases=await db.productPurchase.findMany({where:{userId:u.id},include:{product:true},orderBy:{createdAt:"desc"}});
 const latestPaid=purchases.find(p=>p.paymentStatus==="PAID")||purchases[0];
 if(params.status==="paid"&&latestPaid){
  return <main style={{background:"#fff",minHeight:"100vh",color:"#111"}}><div style={{maxWidth:760,margin:"0 auto",padding:"18px 22px 56px"}}>
   <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"4px 0 34px"}}><Link href="/dashboard" style={{fontSize:24,fontWeight:800,letterSpacing:"0.12em",textDecoration:"none",color:"#111"}}>ELITE</Link><Link href="/inventory" className="btn secondary" style={{borderColor:"#e5e5e5"}}>Menu</Link></header>
   <section style={{textAlign:"center",padding:"12px 0 28px"}}><div style={{width:78,height:78,border:"5px solid #18b83f",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 28px",color:"#18b83f"}}><span style={{fontSize:48,lineHeight:1,fontWeight:800,transform:"translateY(-3px)"}}>✓</span></div><h1 style={{fontSize:"clamp(38px,8vw,58px)",lineHeight:1.05,margin:"0 0 18px",letterSpacing:"-0.04em"}}>Thank You</h1><p style={{fontSize:18,lineHeight:1.55,color:"#555",maxWidth:560,margin:"0 auto"}}>Your vehicle payment has been confirmed. An Elite Auto advisor will reach out to confirm the next steps, delivery or pickup details.</p></section>
   <section style={{marginTop:10}}><div style={{borderRadius:18,overflow:"hidden",background:"#f3f5f6"}}><img src={latestPaid.product.imageUrl} alt={latestPaid.product.name} style={{display:"block",width:"100%",aspectRatio:"16/10",objectFit:"cover"}}/></div><div style={{padding:"24px 4px 0"}}><p style={{fontSize:13,fontWeight:700,letterSpacing:"0.1em",textTransform:"uppercase",color:"#777",marginBottom:8}}>Your vehicle</p><h2 style={{fontSize:30,margin:"0 0 8px",letterSpacing:"-0.025em"}}>{latestPaid.product.name}</h2><p style={{color:"#666",margin:"0 0 14px"}}>Order {latestPaid.reference}</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><span style={{background:"#eaf8ee",color:"#138a32",borderRadius:999,padding:"8px 12px",fontWeight:700}}>Payment confirmed</span><span style={{background:"#f2f2f2",color:"#333",borderRadius:999,padding:"8px 12px"}}>{latestPaid.status}</span></div></div></section>
   <section style={{marginTop:38,paddingTop:28,borderTop:"1px solid #e7e7e7"}}><h2 style={{fontSize:28,margin:"0 0 18px"}}>Explore</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Link href="/inventory" style={{display:"block",padding:18,border:"1px solid #e5e5e5",borderRadius:14,textDecoration:"none",color:"#111"}}><b>Explore vehicles</b><p style={{color:"#666",margin:"8px 0 0"}}>View available Tesla vehicles, colors and configurations.</p></Link><Link href="/dashboard" style={{display:"block",padding:18,border:"1px solid #e5e5e5",borderRadius:14,textDecoration:"none",color:"#111"}}><b>Return to dashboard</b><p style={{color:"#666",margin:"8px 0 0"}}>Review your account and activity.</p></Link></div></section>
  </div></main>;
 }
 return <><div className="topbar"><div><p className="eyebrow">Vehicle purchases</p><h1>My purchases</h1><p className="muted">Track purchase requests, payment status and the next action for each vehicle.</p></div><Link className="btn" href="/inventory">Browse inventory</Link></div><div className="card">{purchases.length?purchases.map(p=><div key={p.id} style={{display:"grid",gridTemplateColumns:"90px 1fr auto",gap:16,alignItems:"center",padding:"16px 0",borderBottom:"1px solid var(--line)"}}><img src={p.product.imageUrl} alt={p.product.name} style={{width:90,height:70,objectFit:"cover",borderRadius:10}}/><div><b>{p.product.name}</b><div className="muted">{p.reference} · {new Date(p.createdAt).toLocaleString()}</div><div style={{marginTop:5}}>{money(Number(p.amount),p.currency)}{p.downPayment?<> · down payment {money(Number(p.downPayment),p.currency)}</>:null}</div></div><div><span className="badge">{p.status}</span><div className="muted" style={{marginTop:6}}>{p.paymentStatus}</div></div></div>):<div className="empty"><h2>No purchase requests</h2><p>Choose a vehicle from inventory to start a purchase request.</p><Link className="btn" href="/inventory">Browse inventory</Link></div>}</div></>;
}